@startuml ChatApp
  object user {
      -ID
      -表示名
      -パスワード
      -ログインする()
      -部屋を作成する()
      -部屋に参加する()
      -部屋から退室する()
      -参加している部屋を表示する()
      -他のユーザを部屋に招待する()
      -他のユーザを部屋から退室させる()
      -ポストを作成する()
      -ポストを削除する()
      -フレンドを表示する()
  }
  object room {
      -ポストを表示する()
      -参加ユーザを表示する()
  }

  object post {
      -ユーザID
      -送信日時
      -本文 [テキスト、画像、音声]
  }

  object friend {
      -ユーザID1
      -ユーザID2
  }

  room "*" o-- "*" user
  room "1" o-- "*" post
  user "1" o-- "*" post
   
@enduml